### PR TITLE
Dev Flow for creating AAD assets

### LINKED ISSUE #1513: Granting Admin Consent to Automation Account fails first time
When you run 
```
./aad-app-reg.sh --name 'TRE' --swaggerui-redirecturl https://mytre.region.cloudapp.azure.com/api/docs/oauth2-redirect --admin-consent --automation-account
```
the first time, it can fail with saying that the automation account has not been created. This is just an aad propogation bug and just needs a wait around it.
This is around Line 764 of the script

**Steps to reproduce**

1. Run the script outlined above to create a new App Registration

### PR DESCRIPTION
**Pull request by ross-p-smith**
# PR for issue #1352
Fixes #1513

## What is being addressed

- new `make auth` which sets up TRE API. SwaggerUI, Automation Account and Workspace.
- Moved some of the AAD functions as a start to slim down the aad-app-reg.sh script.
- SwaggerUI app now has correct user_impersonation for api and workspace
- Add the Application.ReadWrite.OwnedBy permission and grant admin permission to it. This lays the work for the guacamole redirect to be updated by using the Workspace client/secret.

### CODE REVIEW

**Comment by tamirkamara** [comment]
@ross-p-smith Can you explain how the entire follow is going to look like?

File: scripts/aad-app-reg.sh [hunk 1]
```diff
@@ -379,6 +337,7 @@ JSON
 
 declare roleUserReadAll=$(get_msgraph_role "User.Read.All" )
 declare roleDirectoryReadAll=$(get_msgraph_role "Directory.Read.All" )
+declare roleApplicationReadWriteAll=$(get_msgraph_role "Application.ReadWrite.All" )
```
Comment (damoodamoo) [inline scripts/aad-app-reg.sh:340]: Do we need `ReadWrite.All` ? If it's so that this app can create / manage others - I think we'd get away with `Application.ReadWrite.OwnedBy` - bit more tightly scoped to the apps for TRE? Definitions here - https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-4

Comment (ross-p-smith) [reply scripts/aad-app-reg.sh:340]: With OwnedBy
{"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2022-03-28T08:33:23","request-id":"4bd4caa4-bc35-4b5e-90ff-ee17efdcfb67","client-request-id":"4bd4caa4-bc35-4b5e-90ff-ee17efdcfb67"}}}

Comment (ross-p-smith) [reply scripts/aad-app-reg.sh:340]: Put it back to "All" and it works again. :-( I am unsure why - happy to walk through it as may have missed something - could put a note in the code?

Comment (damoodamoo) [reply scripts/aad-app-reg.sh:340]: yea it's not a massive deal - the app is definitely an owner of the one it's trying to modify? but if not let's use `.All` then.

Comment (stuartleeks) [reply scripts/aad-app-reg.sh:340]: I agree that it would be preferable to use `Application.ReadWrite.OwnedBy`.
Sounds like the app isn't the owner of the object it's trying to modify? If so, is that something that we expect will change as this work progresses? (i.e. add a comment in the code and an issue to track re-visiting this once the work is further on)

**Review by stuartleeks — APPROVED** [review]
LGTM
