### PR TITLE
Fix dev container CLI install path and shared services install jq command

### LINKED ISSUE #2724: Shared services pipeline install fails with 409 if status isn't deployed
If try to run the pipeline and a shared service is installed with a status other than deployed the install will proceed and error with a 409. The status should not matter - redeployment should fail.

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #2724

## What is being addressed
- Makes the CLI install path relative in the dev container
- Deploy shared services script not concerned about deployment status
- [x] Update CHANGELOG.md if needed

### CODE REVIEW

File: devops/scripts/deploy_shared_service.sh [hunk 1]
```diff
@@ -49,7 +49,7 @@ if [[ "$last_result" != 0 ]]; then
 fi
 
 deployed_shared_service=$(echo "${get_shared_services_result}" \
-  | jq -r ".sharedServices[] | select(.templateName == \"${template_name}\" and .deploymentStatus == \"deployed\")")
```
Comment (tanya-borisova) [inline devops/scripts/deploy_shared_service.sh:52]: Yeah this condition is something I missed when I was working on this https://github.com/microsoft/AzureTRE/pull/2235/files 
Sorry!

I think the right condition is to check that the status is not "deleted". As if it is "deleted", we can attempt the deployment again, but not in any other case

**Review by tanya-borisova — CHANGES_REQUESTED** [review]
Requested changes as I think the condition in shared services script needs to be changed and not removed

File: devops/scripts/deploy_shared_service.sh (hunk 1 above)
Comment (tanya-borisova) [reply devops/scripts/deploy_shared_service.sh:52]: Actually, if the status is deploymentFailed, we can also attempt the deployment again

Comment (marrobi) [reply devops/scripts/deploy_shared_service.sh:52]: @tanya-borisova and we won't get a 409 in either of those cases?

Comment (marrobi) [reply devops/scripts/deploy_shared_service.sh:52]: Made that change.

**Review by tanya-borisova — APPROVED** [review]

File: devops/scripts/deploy_shared_service.sh [hunk 2]
```diff
@@ -49,7 +49,7 @@ if [[ "$last_result" != 0 ]]; then
...
+  | jq -r ".sharedServices[] | select(.templateName == \"${template_name}\" and (.deploymentStatus != \"deleted\" or .deploymentStatus != \"deploymentFailed\"))")
```
[the remark this answers is not in the document]
Comment (marrobi) [reply devops/scripts/deploy_shared_service.sh:52]: Good catch? I was going by @tanya-borisova comment above. Can you let me know.

[the remark this answers is not in the document]
Comment (tanya-borisova) [reply devops/scripts/deploy_shared_service.sh:52]: it's correct, good spot

[the remark this answers is not in the document]
Comment (marrobi) [reply devops/scripts/deploy_shared_service.sh:52]: I've updated, as think you are correct.
