### PR TITLE
Fix: storage account 403 error when creating new tre env

### LINKED ISSUE #4405: Bootstrap script fails due to AuthorizationPermissionMismatch (403) on Storage Account
**Describe the bug**
The bootstrap script fails on the first run with a 403 AuthorizationPermissionMismatch error when attempting to access the storage account.

**Steps to reproduce**
ci : 
create branch from main got to actions deploy new branch and it will fail. 

1.setup new tre id in .config file
2.run make all

**Azure TRE release version (e.g. v0.14.0 or main):**
main

**Deployed Azure TRE components - click the (i) in the UI:**

### PR DESCRIPTION
**Pull request by ShakutaiGit**
# Resolves #4405

## What is being addressed

- **Ensuring role propagation before execution**: The script now properly waits for both **Storage Account Contributor** and **Storage Blob Data Contributor** roles to be assigned before attempting storage operations.  
- **Refactoring role assignment check**: Instead of checking a single role, the script now verifies **both** roles are assigned before proceeding, reducing failures due to role propagation delays.  

Testing:

- branch before the change (with the issue)  https://github.com/microsoft/AzureTRE/actions/runs/13544133660
- test of a new branch from the PR branch (after the change in the PR) https://github.com/microsoft/AzureTRE/actions/runs/13783862890 https://github.com/microsoft/AzureTRE/actions/runs/13767557310

### CODE REVIEW

File: devops/terraform/bootstrap.sh [hunk 1]
```diff
@@ -28,33 +28,55 @@ else
...
 echo -e "\n\e[34m»»» ⏳ \e[96mWaiting for role assignment to be applied\e[0m..."
-while [ -z "$(check_role_assignment)" ]; do
+while [ -z "$(check_role_assignments)" ]; do
   echo "Waiting for role assignment..."
   sleep 10
 done
 echo "Role assignment applied."
 
+# shellcheck disable=SC1091
+source ../scripts/mgmtstorage_enable_public_access.sh
```
Comment (ashis-kar91) [inline devops/terraform/bootstrap.sh:78]: Any reason for moving it below the role assignments.
I suspect it might fail the role assignment, if bootstrap.sh is rerun after its first execution.
Can you verify and confirm by executing bootstrap.sh more than once.

File: devops/terraform/bootstrap.sh [hunk 2]
```diff
@@ -38,29 +38,67 @@ if [ -n "${ARM_CLIENT_ID:-}" ]; then
...
 az role assignment create --assignee "$USER_OBJECT_ID" \
   --role "Storage Blob Data Contributor" \
   --scope "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_mgmt_resource_group_name/providers/Microsoft.Storage/storageAccounts/$TF_VAR_mgmt_storage_account_name"
 
 # Function to check if the role assignment exists
-check_role_assignment() {
-  az role assignment list --assignee "$USER_OBJECT_ID" --role "Storage Blob Data Contributor" --scope "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_mgmt_resource_group_name/providers/Microsoft.Storage/storageAccounts/$TF_VAR_mgmt_storage_account_name" --query "[].id" --output tsv
+check_role_assignments() {
+  local sbdc
+  sbdc=$(az role assignment list \
```
Comment (marrobi) [inline devops/terraform/bootstrap.sh:53]: Suggestion from copilot, not tested, but makes sense to have a timeout of some sort...

```
# Function to check if the role assignments exist
check_role_assignments() {
  local roles
  roles=$(az role assignment list \
    --assignee "$USER_OBJECT_ID" \
    --scope "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_mgmt_resource_group_name/providers/Microsoft.Storage/storageAccounts/$TF_VAR_mgmt_storage_account_name" \
    --query "[?roleDefinitionName=='Storage Blob Data Contributor' || roleDefinitionName=='Storage Account Contributor'].roleDefinitionName" --output tsv)
  
  if [[ $roles == *"Storage Blob Data Contributor"* && $roles == *"Storage Account Contributor"* ]]; then
    echo "both"
  fi
}

# Wait for the role assignment to be applied with a timeout
echo -e "\n\e[34m»»» ⏳ \e[96mWaiting for role assignment to be applied\e[0m..."
timeout=300  # 5 minutes timeout
start_time=$(date +%s)

while [ -z "$(check_role_assignments)" ]; do
  echo "Waiting for role assignment..."
  sleep 10
  current_time=$(date +%s)
  elapsed_time=$((current_time - start_time))
  if [ $elapsed_time -ge $timeout ]; then
    echo "ERROR: Timeout waiting for role assignments."
    exit 1
  fi
done
echo "Role assignment applied."
```

File: devops/terraform/bootstrap.sh [hunk 3]
```diff
@@ -38,29 +38,67 @@ if [ -n "${ARM_CLIENT_ID:-}" ]; then
...
 # Wait for the role assignment to be applied
 echo -e "\n\e[34m»»» ⏳ \e[96mWaiting for role assignment to be applied\e[0m..."
-while [ -z "$(check_role_assignment)" ]; do
+while [ -z "$(check_role_assignments)" ]; do
   echo "Waiting for role assignment..."
   sleep 10
 done
 echo "Role assignment applied."
-
+sleep 30
```
Comment (marrobi) [inline devops/terraform/bootstrap.sh:79]: Why do we need to sleep if we are retrying below?

File: devops/terraform/bootstrap.sh [hunk 4]
```diff
@@ -38,29 +38,67 @@ if [ -n "${ARM_CLIENT_ID:-}" ]; then
 else
     USER_OBJECT_ID=$(az ad signed-in-user show --query id --output tsv)
 fi
+
+az role assignment create --assignee "$USER_OBJECT_ID" \
```
Comment (marrobi) [inline devops/terraform/bootstrap.sh:42]: Did you work out why this is required? I thought the object ID that creates the storage account should have sufficient permissions?

**Review by marrobi — COMMENTED** [review]
Couple of comments. Thanks for looking into making this more robust.

File: devops/terraform/bootstrap.sh (hunk 2 above)
Comment (ShakutaiGit) [reply devops/terraform/bootstrap.sh]: Liked it, Adopted.

File: devops/terraform/bootstrap.sh (hunk 3 above)
Comment (ShakutaiGit) [reply devops/terraform/bootstrap.sh]: removed.

File: .github/actions/devcontainer_run_command/action.yml [hunk 5]
```diff
@@ -145,14 +145,14 @@ runs:
...
-      if: contains(inputs.COMMAND, 'bootstrap') != true
+      if: contains(inputs.COMMAND, 'make bootstrap') != true
       with:
         creds: ${{ inputs.AZURE_CREDENTIALS }}
         environment: "${{ env.AZURE_ENVIRONMENT }}"
 
     - name: ACR Login
       shell: bash
-      if: contains(inputs.COMMAND, 'bootstrap') != true
+      if: contains(inputs.COMMAND, 'make bootstrap') != true
```
Comment (LizaShak) [inline .github/actions/devcontainer_run_command/action.yml]: Mmm but that was part of another PR isn't it?

File: devops/terraform/bootstrap.sh [hunk 6]
```diff
@@ -38,30 +81,44 @@ if [ -n "${ARM_CLIENT_ID:-}" ]; then
...
+  --role "Storage Account Contributor" \
```
Comment (LizaShak) [inline devops/terraform/bootstrap.sh:86]: why the role change? Adding a screenshot to show diff between the two roles 
image

Comment (ShakutaiGit) [reply devops/terraform/bootstrap.sh:86]: Removed.

**Comment by ShakutaiGit** [comment]
> 🤖 pr-bot 🤖
> 
> 🏃 Running tests: https://github.com/microsoft/AzureTRE/actions/runs/13783417156 (with refid `ecb751e8`)
> 
> (in response to [this comment](https://github.com/microsoft/AzureTRE/pull/4406#issuecomment-2713118510) from @ShakutaiGit)

tests passed

File: devops/terraform/bootstrap.sh [hunk 7]
```diff
@@ -3,6 +3,50 @@ set -o errexit
...
+      return 0
+    fi
+    sleep "$sleep_time"
+    sleep_time=$((sleep_time * 2))
+  done
+  return 1
+}
+
+init_terraform() {
+  terraform_output=$(terraform init -input=false -reconfigure 2>&1)
```
Comment (yuvalyaron) [inline devops/terraform/bootstrap.sh:22]: don't we need the `-backend=true` anymore?

File: devops/terraform/bootstrap.sh [hunk 8]
```diff
@@ -31,37 +75,48 @@ fi
 # shellcheck disable=SC1091
 source ../scripts/mgmtstorage_enable_public_access.sh
 
-# Grant user blob data contributor permissions
+# Grant user blob data contributor permissions.
```
Comment (yuvalyaron) [inline devops/terraform/bootstrap.sh:78]: remove the dot

**Review by yuvalyaron — APPROVED** [review]
