### PR TITLE
Fix check-param target

### LINKED ISSUE #2156: bundle-check-param target doesn't use MAKEFILE_DIR prefix
**Describe the bug**
As stated which causes failures when embedding the TRE in another repo.

### PR DESCRIPTION
**Pull request by tamirkamara**
Fixes #2156

## What is being addressed

1. DB migrate script works without a valid SSL
2. check param make target to include the right prefix and enable this makefile to be included in a parent one

### CODE REVIEW

**Comment by ross-p-smith** [comment]
Ah! I had a PR with some of this too!

**Comment by tamirkamara** [comment]
/test-force-approve
Included changes are not tested via CI deployment anyway.

File: devops/scripts/migrate_state_store.sh [hunk 1]
```diff
@@ -68,6 +68,10 @@ if [[ -z ${tre_url:-} ]]; then
     usage
 fi
 
+if [[ -n ${insecure+x} ]]; then
+    options="-k"
```
Comment (ross-p-smith) [inline devops/scripts/migrate_state_store.sh:72]: Will this now conflict with my change?

Comment (tamirkamara) [reply devops/scripts/migrate_state_store.sh]: fixed

File: devops/scripts/migrate_state_store.sh [hunk 2]
```diff
@@ -78,7 +82,10 @@ if [ -z "${access_token:-}" ]; then
   access_token=${ACCESS_TOKEN}
 fi
 
-migrate_result=$(curl -i -X "POST" "${tre_url}/api/migrations" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ${access_token}" ${options})
+curl_retry_settings=(--retry 3 --retry-max-time 300 --max-time 90)
+
```
[the remark this answers is not in the document]
Comment (tamirkamara) [reply devops/scripts/migrate_state_store.sh]: fixed. with the array no extra space will be added.

**Review by marrobi — APPROVED** [review]
LGTM

**Comment by tamirkamara** [comment]
/test-force-approve
Included changes are not tested via CI deployment anyway.
