### PR TITLE
Azure ML Linting Fixes and conditional NSG rules

### LINKED ISSUE #2641: Azure ML templates have linting issues
the Azure ML templates have linting issues, which means when custom copies are made linting fails.

### PR DESCRIPTION
**Pull request by marrobi**
# Resolves #2641

## What is being addressed
- Fix linting
- Remove unused ACR module
- Make NSG rules conditional based on if exposed externally so AML check in portal passes.
- Fix error in NSG script missing direction variable.

### CODE REVIEW

File: templates/workspace_services/azureml/terraform/deploy.sh [hunk 1]
```diff
@@ -1,9 +1,17 @@
+#!/bin/bash
+set -o errexit
+set -o pipefail
+set -o nounset
+
 export TF_LOG=""
 
+# This variables are loaded in for us
```
Comment (martinpeck) [inline templates/workspace_services/azureml/terraform/deploy.sh:8]: nit: should be THESE rather than

File: templates/workspace_services/azureml/terraform/get_nsg_priorities.sh [hunk 2]
```diff
@@ -1,14 +1,21 @@
...
+set -o pipefail
+set -o nounset
 
-set -e
 
 eval "$(jq -r '@sh "nsg_name=\(.nsg_name) resource_group_name=\(.resource_group_name) nsg_rule_name=\(.nsg_rule_name) direction=\(.direction)"')"
-if NSG_RULE=$(az network nsg rule show -g $resource_group_name --nsg-name $nsg_name --name $nsg_rule_name -o json); then
-    NSG_RULE_PRIORITY=$(echo $NSG_RULE | jq '.priority')
+
+# This variables are loaded in for us
```
Comment (martinpeck) [inline templates/workspace_services/azureml/terraform/get_nsg_priorities.sh:9]: nit: Same suggest regarding THESE rather than THIS

File: templates/workspace_services/azureml/user_resources/aml_compute/terraform/deploy.sh [hunk 3]
```diff
@@ -1,6 +1,14 @@
...
+set -o pipefail
+set -o nounset
+
 export TF_LOG=""
+
+# This variables are loaded in for us
+# shellcheck disable=SC2154
 terraform init -input=false -backend=true -reconfigure \
-    -backend-config="resource_group_name=$TF_VAR_mgmt_resource_group_name" \
+    -backend-config="resource_group_name=${TF_VAR_mgmt_resource_group_name}" \
```
Comment (martinpeck) [inline templates/workspace_services/azureml/user_resources/aml_compute/terraform/deploy.sh:11]: just curious: why does this line get the `{` brackets added, but others in this command (and other examples in this PR) not?

File: templates/workspace_services/azureml/terraform/deploy.sh (hunk 1 above)
Comment (marrobi) [reply templates/workspace_services/azureml/terraform/deploy.sh:8]: done.

File: templates/workspace_services/azureml/terraform/get_nsg_priorities.sh (hunk 2 above)
Comment (marrobi) [reply templates/workspace_services/azureml/terraform/get_nsg_priorities.sh:9]: done

**Review by martinpeck — APPROVED** [review]
LGTM
